global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'jhipster'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: /management/prometheus
    static_configs:
      - targets:
          - localhost:8080
