version: '3.8'
services:
  currencyconverter-prometheus:
    image: prom/prometheus:v2.26.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
    ports:
      - 127.0.0.1:9090:9090
    network_mode: 'host' # to test locally running service
  currencyconverter-grafana:
    image: grafana/grafana:7.5.2
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - 127.0.0.1:3000:3000
    network_mode: 'host' # to test locally running service
